version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - deploy:
          name: install package for dev
          command: pip install .[dev]
      - run:
          name: Run tests
          command: pytest

workflows:
  github-push:
    jobs:
      - build-and-test
